/* Public exhibition, evolved from the original gallery and lightbox. */
(async function(){
const $=s=>document.querySelector(s);
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let raw=window.PORTFOLIO,overrides={},previewTarget=null;
if(location.hash==='#studio-preview'&&window.opener){
  const draft=await new Promise(resolve=>{const timeout=setTimeout(()=>resolve(null),4000);function receive(event){if(event.source!==window.opener||event.data?.type!=='aki-preview-data')return;if(location.origin!=='null'&&event.origin!==location.origin)return;clearTimeout(timeout);window.removeEventListener('message',receive);resolve(event.data)}window.addEventListener('message',receive);window.opener.postMessage({type:'aki-preview-ready'},location.origin==='null'?'*':location.origin)});
  if(draft){raw=draft.content;overrides=draft.images||{};previewTarget=draft.target;const note=document.createElement('p');note.className='preview-notice';note.textContent='Studio preview · unsaved content · not published';document.body.prepend(note)}
}
let data;try{data=PortfolioContent.normalize(raw)}catch(error){$('#featured').textContent='This collection could not be opened. Please check the content file in the studio.';return}
const photos=data.photos,photoMap=new Map(photos.map(p=>[p.id,p]));
const safeURL=value=>{if(!value)return '';try{const url=new URL(value,location.href);return ['http:','https:','file:'].includes(url.protocol)?url.href:''}catch{return ''}};
const imageURL=p=>typeof overrides[p.id]==='string'&&overrides[p.id].startsWith('blob:')?overrides[p.id]:safeURL(p.src);
const formatDate=value=>{if(!PortfolioContent.realDate(value))return value;return new Date(value+'T12:00:00').toLocaleDateString('en-GB',{day:'2-digit',month:'long',year:'numeric'})};
const sampleLabel=item=>item.sample?'<span class="sample-label">Sample</span>':'';
function photoMarkup(p,{featured=false,framed=false,index=0}={}){return `<figure class="${featured?'featured-figure':escape(p.shape)+' reveal'} ${framed?'glass-frame':''}"><button class="photo-button" data-photo="${photos.indexOf(p)}" aria-label="View ${escape(p.title)}"><img src="${escape(imageURL(p))}" alt="${escape(p.alt)}" ${featured?'fetchpriority="high"':'loading="lazy"'} decoding="async"></button><figcaption><div><h3>${escape(p.title)}</h3>${p.place?`<p>${escape(p.place)}</p>`:''}</div><span class="photo-number">${String(index+1).padStart(2,'0')}</span></figcaption></figure>`}
document.querySelectorAll('.wordmark,.signature').forEach(el=>{el.textContent=data.name;if(el.tagName==='A')el.setAttribute('aria-label',data.name+' home')});
$('#intro').textContent=data.intro;$('#intro').style.whiteSpace='pre-line';$('#about-copy').textContent=data.about;
const copyTargets={siteLabel:'.header-label,footer>span',heroEyebrow:'.opening-text>.eyebrow',heroNote:'.intro-note',japaneseNote:'.japanese',archiveTitle:'#archive-title',archiveEyebrow:'#photographs .section-heading>.eyebrow',aboutLabel:'.about>.eyebrow',journalEyebrow:'.journal-heading>.eyebrow',journalTitle:'.journal-heading>h2',journalNote:'.journal-heading>p',sampleNotice:'.demo-note',collectionsTitle:'#collections-title',collectionsNote:'.collections-note'};
for(const [key,selector]of Object.entries(copyTargets))document.querySelectorAll(selector).forEach(el=>el.textContent=data.copy[key]);
function linkText(selector,text,arrow){const el=$(selector);el.replaceChildren(document.createTextNode(text+' '));const span=document.createElement('span');span.textContent=arrow;span.setAttribute('aria-hidden','true');el.append(span)}
linkText('.journal-link',data.copy.journalNav,'↗');linkText('.below-hero>a',data.copy.archiveLink,'↓');linkText('footer>a:last-of-type',data.copy.backToTop,'↑');
$('.below-hero>span:first-child').firstChild.textContent=data.copy.featuredLabel+' · ';
document.title=data.name+' — '+data.copy.siteLabel;
const showcase=data.showcaseIds.map(id=>photoMap.get(id));let showcaseIndex=0;
function renderShowcase(){if(!showcase.length){$('#featured').innerHTML='<div class="showcase-empty"><p>The first photographs will find their place here.</p></div>';$('#feature-year').textContent='A beginning';return}const p=showcase[showcaseIndex];$('#featured').innerHTML=photoMarkup(p,{featured:true})+`<div class="showcase-caption"><span>${escape(p.title)} ${sampleLabel(p)}</span>${showcase.length>1?`<div class="showcase-controls" role="group" aria-label="Selected photographs">${showcase.map((item,i)=>`<button class="glass-control" data-showcase-index="${i}" aria-label="Show ${escape(item.title)}" aria-pressed="${i===showcaseIndex}">${String(i+1).padStart(2,'0')}</button>`).join('')}</div>`:''}</div>`;$('#feature-year').textContent=String(showcase.length).padStart(2,'0')+' frames';wireImageErrors($('#featured'));}
renderShowcase();$('#featured').addEventListener('click',e=>{const control=e.target.closest('[data-showcase-index]');if(control){showcaseIndex=Number(control.dataset.showcaseIndex);renderShowcase();$('#featured').querySelector(`[data-showcase-index="${showcaseIndex}"]`).focus({preventScroll:true})}});
const posts=data.posts.filter(p=>p.published).sort((a,b)=>b.date.localeCompare(a.date));
const years=[...new Set(posts.map(p=>Number(p.date.slice(0,4))).filter(Number.isFinite))].sort((a,b)=>b-a);
function postSummary(post){const p=photoMap.get(post.photoIds[0]);return `<article class="post-summary reveal"><a class="post-image ${escape(p?.shape||'landscape')}" href="#post/${encodeURIComponent(post.id)}" aria-label="Open ${escape(post.title)}">${p?`<img src="${escape(imageURL(p))}" alt="${escape(p.alt)}" loading="lazy" decoding="async">`:''}</a><div class="post-summary-text"><p class="eyebrow"><time datetime="${escape(post.date)}">${escape(formatDate(post.date))}</time> ${sampleLabel(post)}</p><h3><a href="#post/${encodeURIComponent(post.id)}">${escape(post.title)}</a></h3>${post.description?`<p class="post-excerpt">${escape(post.description.length>220?post.description.slice(0,217)+'…':post.description)}</p>`:''}<a class="story-link" href="#post/${encodeURIComponent(post.id)}">${post.photoIds.length} photograph${post.photoIds.length===1?'':'s'} <span aria-hidden="true">↗</span></a></div></article>`}
for(const year of years){const option=document.createElement('option');option.value=year;option.textContent=year;$('#year-select').append(option);const entries=posts.filter(p=>Number(p.date.slice(0,4))===year);$('#archive').insertAdjacentHTML('beforeend',`<section class="year-section" id="year-${year}" aria-label="Posts from ${year}"><div class="year-marker">${year}<small>${entries.length} ${entries.length===1?'entry':'entries'}</small></div><div class="year-gallery post-feed">${entries.map(postSummary).join('')}</div></section>`)}
if(!posts.length)$('#archive').innerHTML='<p class="quiet-empty">The journey starts here. New photographic entries will appear as they are made.</p>';
$('#year-select').addEventListener('change',e=>{const target=e.target.value?$('#year-'+e.target.value):$('#photographs');target?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})});
const collections=data.collections.filter(c=>c.published);
$('#collection-wall').innerHTML=collections.map((collection,i)=>{const p=photoMap.get(collection.coverId);return `<article class="collection-preview reveal"><a class="collection-frame" href="#collection/${encodeURIComponent(collection.id)}" aria-label="Explore ${escape(collection.title)}">${p?`<img src="${escape(imageURL(p))}" alt="${escape(p.alt)}" loading="lazy" decoding="async">`:''}</a><div class="collection-caption"><div><p class="eyebrow">Collection ${String(i+1).padStart(2,'0')} ${sampleLabel(collection)}</p><h3><a href="#collection/${encodeURIComponent(collection.id)}">${escape(collection.title)}</a></h3>${collection.subtitle?`<p>${escape(collection.subtitle)}</p>`:''}</div><a class="glass-control" href="#collection/${encodeURIComponent(collection.id)}" aria-label="Explore ${escape(collection.title)}">↗</a></div></article>`}).join('')||'<p class="quiet-empty">A space for photographs that belong together.</p>';
const journal=data.journal.filter(j=>j.published).sort((a,b)=>b.date.localeCompare(a.date));
$('#journal-entries').innerHTML=journal.map((entry,i)=>`<details class="journal-entry reveal" ${i===0?'open':''}><summary><time datetime="${escape(entry.date)}">${escape(formatDate(entry.date))} ${entry.sample?'· Sample':''}</time><h3>${escape(entry.title)}</h3></summary><p class="entry-body">${escape(entry.body)}</p></details>`).join('')||'<p class="quiet-empty">A few thoughts will find their way here soon.</p>';
$('.demo-note').hidden=![...showcase,...posts,...collections,...journal].some(item=>item.sample);
let active=0,viewerPhotos=showcase,storyPhotos=[],previousFocus=null;
const dialog=$('#lightbox'),story=$('#story-view');
function showPhoto(index){if(!viewerPhotos.length)return;active=(index+viewerPhotos.length)%viewerPhotos.length;const p=viewerPhotos[active];$('#lightbox-image').src=imageURL(p);$('#lightbox-image').alt=p.alt;$('#lightbox-title').textContent=p.title;$('#lightbox-meta').textContent=[p.place,p.sample?'Sample photograph':p.capturedOn?formatDate(p.capturedOn):p.date?[p.date,p.year].filter(Boolean).join(' '):''].filter(Boolean).join(' · ');$('#lightbox-story').textContent=p.story;$('#lightbox-story').hidden=!p.story;$('#lightbox-count').textContent=`${String(active+1).padStart(2,'0')} / ${String(viewerPhotos.length).padStart(2,'0')}`;$('#lightbox-credit').innerHTML=p.credit?`Photograph by ${p.source?`<a href="${escape(safeURL(p.source))}" target="_blank" rel="noopener noreferrer">${escape(p.credit)} ↗</a>`:escape(p.credit)}`:'';$('.previous').hidden=$('.next').hidden=viewerPhotos.length<2;dialog.scrollTop=0;}
document.addEventListener('click',event=>{const button=event.target.closest('[data-photo]');if(!button)return;const p=photos[Number(button.dataset.photo)];viewerPhotos=button.closest('#story-view')?storyPhotos:showcase;if(!viewerPhotos.includes(p))viewerPhotos=[p];previousFocus=button;showPhoto(viewerPhotos.indexOf(p));dialog.showModal()});
$('.close').addEventListener('click',()=>dialog.close());$('.previous').addEventListener('click',()=>showPhoto(active-1));$('.next').addEventListener('click',()=>showPhoto(active+1));dialog.addEventListener('keydown',e=>{if(e.key==='ArrowLeft'){e.preventDefault();showPhoto(active-1)}if(e.key==='ArrowRight'){e.preventDefault();showPhoto(active+1)}});dialog.addEventListener('close',()=>previousFocus?.focus({preventScroll:true}));
function openStory(kind,id,allowDraft=false){const item=(kind==='post'?data.posts:data.collections).find(item=>item.id===id&&(allowDraft||item.published));if(!item)return;storyPhotos=item.photoIds.map(id=>photoMap.get(id));$('#story-content').className=kind==='post'?'magazine':'collection-exhibition';$('#story-content').innerHTML=`<div class="story-heading"><p class="eyebrow">${kind==='post'?escape(formatDate(item.date)):'A collection'} ${sampleLabel(item)}</p><h1 id="story-title">${escape(item.title||'Untitled')}</h1>${item.subtitle?`<p class="story-subtitle">${escape(item.subtitle)}</p>`:''}${item.location?`<p class="story-location">${escape(item.location)}</p>`:''}${item.description?`<p class="story-introduction">${escape(item.description)}</p>`:''}</div><div class="editorial-photos">${storyPhotos.map((p,i)=>photoMarkup(p,{index:i,framed:kind==='collection'})).join('')||'<p class="quiet-empty">Add photographs in the studio to fill this story.</p>'}</div><p class="story-end">${storyPhotos.length} photographs · ${escape(data.name)}</p>`;if(!story.open)story.showModal();story.scrollTop=0;wireImageErrors(story);reveal(story);$('.story-close').focus({preventScroll:true});}
function closeStory(){if(dialog.open)dialog.close();if(story.open)story.close();if(/^#(post|collection)\//.test(location.hash))history.replaceState(null,'',location.pathname+location.search+'#'+(location.hash.startsWith('#post/')?'photographs':'collections'))}
$('.story-close').addEventListener('click',closeStory);story.addEventListener('cancel',event=>{event.preventDefault();closeStory()});$('.story-toolbar .wordmark').addEventListener('click',closeStory);
function route(){const match=location.hash.match(/^#(post|collection)\/(.+)$/);if(match){try{openStory(match[1],decodeURIComponent(match[2]))}catch{closeStory()}}else if(story.open)closeStory()}
window.addEventListener('hashchange',route);route();if(previewTarget)openStory(previewTarget.kind,previewTarget.id,true);
function wireImageErrors(root){root.querySelectorAll('img').forEach(img=>{img.addEventListener('error',()=>{img.classList.add('failed-image');img.alt='Photograph unavailable — '+img.alt},{once:true})})}
function reveal(root){if(!('IntersectionObserver'in window)||matchMedia('(prefers-reduced-motion: reduce)').matches)return;document.body.classList.add('motion-ready');const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.06});root.querySelectorAll('.reveal').forEach(el=>observer.observe(el))}
wireImageErrors(document);reveal(document);window.portfolioReady=true;window.dispatchEvent(new Event('portfolio-ready'));
})();
