window.PORTFOLIO = {
  "name": "アキ",
  "intro": "We do not remember days,\nwe remember moments",
  "about": "I’m at the beginning of a photography journey. Learning to notice the light, to stay a little longer, and to make photographs that remember how a place felt.",
  "copy": {
    "siteLabel": "Photographs & field notes",
    "heroEyebrow": "A collection of quiet things",
    "heroNote": "A photography journey, just beginning.\nA little closer. A little slower.",
    "featuredLabel": "Selected photographs",
    "archiveLink": "Wander through",
    "japaneseNote": "自然の中で、立ち止まる。",
    "archiveTitle": "The days, as they unfold",
    "archiveEyebrow": "A photographic journal",
    "aboutLabel": "A note from アキ",
    "journalNav": "Journal",
    "journalEyebrow": "Not everything becomes a photograph",
    "journalTitle": "Notes from\nout there.",
    "journalNote": "Loose thoughts, written down\nbefore they disappear.",
    "backToTop": "Back to the beginning",
    "collectionsTitle": "Small bodies of work",
    "collectionsNote": "Photographs in conversation with one another.",
    "sampleNotice": "Sample exhibition · Photographs courtesy of Unsplash. Sample posts and collections are for demonstration."
  },
  "photos": [
    {
      "id": "forest-light",
      "title": "Where the light settles",
      "place": "Among the trees",
      "date": "Late summer",
      "src": "photos/forest-light.jpg",
      "alt": "Sunlight drifting through a misty forest canopy",
      "credit": "Pascal Debrunner",
      "source": "https://unsplash.com/photos/sunlight-streams-through-a-misty-forest-canopy-vBtJYXG6yPA",
      "year": 2026,
      "shape": "wide",
      "capturedOn": "",
      "story": "",
      "sample": true
    },
    {
      "id": "first-light",
      "title": "Before the world wakes",
      "place": "At the water’s edge",
      "date": "Early summer",
      "src": "photos/first-light.jpg",
      "alt": "A still mountain lake wrapped in morning mist",
      "credit": "Anthony Gomez",
      "source": "https://unsplash.com/photos/misty-lake-with-mountains-and-trees-at-dawn-uyxJl4SBE3s",
      "year": 2026,
      "shape": "landscape",
      "capturedOn": "",
      "story": "",
      "sample": true
    },
    {
      "id": "little-green",
      "title": "A small unfolding",
      "place": "Along the trail",
      "date": "Spring",
      "src": "photos/little-green.jpg",
      "alt": "A close view of the delicate green fronds of a fern",
      "credit": "Catarina Carvalho",
      "source": "https://unsplash.com/photos/close-up-photography-of-fern-plant-nDTPFJeP8Zw",
      "year": 2026,
      "shape": "portrait",
      "capturedOn": "",
      "story": "",
      "sample": true
    },
    {
      "id": "tideline",
      "title": "Nothing stays, nothing leaves",
      "place": "The coast",
      "date": "Autumn",
      "src": "photos/tideline.jpg",
      "alt": "Ocean waves breaking into layers of white foam",
      "credit": "Christoffer Engström",
      "source": "https://unsplash.com/photos/photo-of-ocean-waves-at-daytime-wc9avd2RaN0",
      "year": 2025,
      "shape": "wide",
      "capturedOn": "",
      "story": "A sample photograph from the water-and-air collection. Add your own words here when you replace it with a photograph from your journey.",
      "sample": true
    },
    {
      "id": "woodland",
      "title": "Taking the long way",
      "place": "In the woods",
      "date": "Summer",
      "src": "photos/woodland.jpg",
      "alt": "Green trees and dense foliage in a quiet woodland",
      "credit": "William Daigneault",
      "source": "https://unsplash.com/photos/green-trees-in-forest-Omlu0KHlUiQ",
      "year": 2025,
      "shape": "portrait",
      "capturedOn": "",
      "story": "",
      "sample": true
    },
    {
      "id": "snowline",
      "title": "A quieter kind of distance",
      "place": "Above the snowline",
      "date": "Winter",
      "src": "photos/snowline.jpg",
      "alt": "A rugged mountain summit covered in snow",
      "credit": "Austin Smart",
      "source": "https://unsplash.com/photos/snow-covered-mountain--rIC_DZaUW8",
      "year": 2024,
      "shape": "wide",
      "capturedOn": "",
      "story": "",
      "sample": true
    },
    {
      "id": "2f0a5ada-2984-4e1e-88c3-1ebcaae2b815",
      "title": "Gumamela",
      "place": "",
      "date": "",
      "src": "photos/420deb37-Gumamela.jpg",
      "alt": "inconspicuous",
      "credit": "",
      "source": "",
      "year": 2026,
      "shape": "landscape",
      "capturedOn": "",
      "story": "",
      "sample": false
    },
    {
      "id": "331ca134-a3e8-48ba-8bed-4742bbee169d",
      "title": "Alternanthera Brasiliana",
      "place": "",
      "date": "",
      "src": "photos/2aaabcf1-Alternanthera-Brasiliana.jpg",
      "alt": "inconspicuous",
      "credit": "",
      "source": "",
      "year": 2026,
      "shape": "landscape",
      "capturedOn": "",
      "story": "",
      "sample": false
    },
    {
      "id": "51bca699-2cb7-4eef-a4b4-9dac76b95c98",
      "title": "Crape Myrtle",
      "place": "",
      "date": "",
      "src": "photos/fe243388-Crape-Myrtle.jpg",
      "alt": "inconspicuous",
      "credit": "",
      "source": "",
      "year": 2026,
      "shape": "landscape",
      "capturedOn": "",
      "story": "",
      "sample": false
    },
    {
      "id": "671e1313-2765-45fb-a5ae-f1b94ea4c939",
      "title": "Rose",
      "place": "",
      "date": "",
      "src": "photos/644477af-Rose.jpg",
      "alt": "inconspicuous",
      "credit": "",
      "source": "",
      "year": 2026,
      "shape": "landscape",
      "capturedOn": "",
      "story": "",
      "sample": false
    }
  ],
  "journal": [],
  "featuredId": "331ca134-a3e8-48ba-8bed-4742bbee169d",
  "schemaVersion": 3,
  "showcaseIds": [
    "331ca134-a3e8-48ba-8bed-4742bbee169d",
    "51bca699-2cb7-4eef-a4b4-9dac76b95c98",
    "671e1313-2765-45fb-a5ae-f1b94ea4c939",
    "2f0a5ada-2984-4e1e-88c3-1ebcaae2b815"
  ],
  "posts": [
    {
      "id": "first-field-notes",
      "title": "A first walk, a slower look",
      "description": "A sample entry for the beginning of a journey. Three photographs, one quiet walk. Replace these with your own images and a few words about what caught your attention.",
      "photoIds": [
        "forest-light",
        "little-green",
        "woodland"
      ],
      "published": true,
      "sample": true,
      "date": "2026-09-09",
      "location": "Among the trees"
    }
  ],
  "collections": [
    {
      "id": "water-and-air",
      "title": "Between water and air",
      "description": "A sample collection. A lake, the sea, a snow-covered ridge: three photographs brought together as a visual conversation. Collections live independently of the dated journal.",
      "photoIds": [
        "tideline",
        "first-light",
        "snowline"
      ],
      "published": true,
      "sample": true,
      "subtitle": "Studies in stillness and movement",
      "coverId": "tideline"
    }
  ]
};
