window.PORTFOLIO = {
  "name": "アキ",
  "intro": "We do not remember days, we remember moments.",
  "about": "I’m at the beginning of a photography journey. Learning to notice the light, to stay a little longer, and to make photographs that remember how a place felt.",
  "copy": {
    "siteLabel": "Photographs & field notes",
    "heroEyebrow": "A collection of quiet things",
    "heroNote": "A photography journey, just beginning.\nA little closer. A little slower.",
    "featuredLabel": "Selected photographs",
    "archiveLink": "Wander through",
    "japaneseNote": "自然の中で、立ち止まる。",
    "archiveTitle": "The days, as they unfold",
    "archiveEyebrow": "A photographic journal",
    "aboutLabel": "A note from アキ",
    "journalNav": "Journal",
    "journalEyebrow": "Not everything becomes a photograph",
    "journalTitle": "Notes from\nout there.",
    "journalNote": "Loose thoughts, written down\nbefore they disappear.",
    "backToTop": "Back to the beginning",
    "collectionsTitle": "Small bodies of work",
    "collectionsNote": "Photographs in conversation with one another.",
    "sampleNotice": "Sample exhibition · Photographs courtesy of Unsplash. Sample posts and collections are for demonstration."
  },
  "photos": [
    {
      "id": "2f0a5ada-2984-4e1e-88c3-1ebcaae2b815",
      "title": "Gumamela",
      "place": "",
      "date": "",
      "src": "photos/420deb37-Gumamela.jpg",
      "alt": "inconspicuous",
      "credit": "",
      "source": "",
      "year": 2026,
      "shape": "landscape",
      "capturedOn": "",
      "story": "",
      "sample": false
    },
    {
      "id": "331ca134-a3e8-48ba-8bed-4742bbee169d",
      "title": "Alternanthera Brasiliana",
      "place": "",
      "date": "",
      "src": "photos/2aaabcf1-Alternanthera-Brasiliana.jpg",
      "alt": "inconspicuous",
      "credit": "",
      "source": "",
      "year": 2026,
      "shape": "landscape",
      "capturedOn": "",
      "story": "",
      "sample": false
    },
    {
      "id": "51bca699-2cb7-4eef-a4b4-9dac76b95c98",
      "title": "Crape Myrtle",
      "place": "",
      "date": "",
      "src": "photos/fe243388-Crape-Myrtle.jpg",
      "alt": "inconspicuous",
      "credit": "",
      "source": "",
      "year": 2026,
      "shape": "landscape",
      "capturedOn": "",
      "story": "",
      "sample": false
    },
    {
      "id": "671e1313-2765-45fb-a5ae-f1b94ea4c939",
      "title": "Rose",
      "place": "",
      "date": "",
      "src": "photos/644477af-Rose.jpg",
      "alt": "inconspicuous",
      "credit": "",
      "source": "",
      "year": 2026,
      "shape": "landscape",
      "capturedOn": "",
      "story": "",
      "sample": false
    }
  ],
  "journal": [],
  "featuredId": "2f0a5ada-2984-4e1e-88c3-1ebcaae2b815",
  "schemaVersion": 3,
  "showcaseIds": [
    "2f0a5ada-2984-4e1e-88c3-1ebcaae2b815",
    "331ca134-a3e8-48ba-8bed-4742bbee169d",
    "51bca699-2cb7-4eef-a4b4-9dac76b95c98",
    "671e1313-2765-45fb-a5ae-f1b94ea4c939"
  ],
  "posts": [],
  "collections": []
};
